name: Update Timestamp

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Update timestamp
      run: |
        sed -i "s/<span class=\"last-update-text\" id=\"last-update\" data-timestamp=\"[0-9]*\">today<\/span>/<span class=\"last-update-text\" id=\"last-update\" data-timestamp=\"$(date +%s)\">$(date +"%B %d, %Y")<\/span>/" ./index.html
        git add index.html
        git commit -m "Update timestamp" --no-verify
        git push origin main  # Adjust the branch name if needed
